name: CI

on:
  push:
    branches:
      - 'main'
      - 'release-v**'
  pull_request:
    
jobs:
  build:
    name: Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout powsybl-network-area-diagram latest sources
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-network-area-diagram
          ref: refs/heads/main

      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build and install powsybl-network-area-diagram with Maven
        run: mvn --batch-mode -DskipTests=true --file ../powsybl-network-area-diagram/pom.xml install

      - name: Build with Maven
        run: mvn --file network-area-diagram-viewer --batch-mode -P jacoco,checks package

      - name: Run SonarCloud analysis
        if: matrix.os == 'ubuntu-latest'
        run: >
          mvn --file network-area-diagram-viewer --batch-mode -Pjacoco verify sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=com.powsybl:powsybl-dev-tools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
